### ISSUE TITLE
vbgs/vbge: Replace vbge.NotifyGroup + relativePosition slices to combined vbge.NotifyGroupLocated

### ISSUE THREAD

**Issue by harwoeck** [vikebot/vikebot#10]
**Describe the current situation**
In situations where we need a `vbge.NotifyGroup`  and their relative positions to us (this happens regularly) we return a `vbge.NotifyGroup` **AND** a slice containing `vbge.Location`s. Afterwards iterators use the index to match a `vbge.Player` (inside the `vbge.NotifyGroup`) with the associated relative location in the slice. This are extremely bad practices and should be replaced.

**Expected**
Return a combined structure like:

```go
type NotifyGroupLocated []*NotifyGroupLocatedEntity

type NotifyGroupLocatedEntity struct {
	Player *Player
	Loc    *Location
}
```

**Additional context**
This was done during bug-fixing just before a live-demo
![image](https://user-images.githubusercontent.com/16159211/50057609-3f811d00-016d-11e9-99f5-6e82f88771c7.png)

**Comment by andileeb** [comment]
Fixed in https://github.com/vikebot/vbgs/pull/3
